### ISSUE TITLE
`st_uid`와 `st_gid`에 접근 불가능한 경우 출력 문의

### ISSUE THREAD

**Issue by peng-u-0807** [SNU-ARC/2024_spring_sysprog_Lab2#25]
안녕하세요, `README.md` 중 아래와 비슷한 출력 결과를 얻고자 테스트하는 중이었습니다.

```
$ dirtree -v -s demo3
Name                                                        User:Group           Size     Perms Type 
----------------------------------------------------------------------------------------------------
demo3
  dir1                                                   sysprog:sysprog         4096 --x------  d
    ERROR: Permission denied
  dir2                                                   sysprog:sysprog         4096 r--------  d
    file1                                               Permission denied
    file2                                               Permission denied
    file3                                               Permission denied
  dir3                                                   sysprog:sysprog         4096 rwx------  d
    file4                                                sysprog:sysprog            0 -----x---   
    file5                                                sysprog:sysprog            0 ----w----   
    file6                                                sysprog:sysprog            0 ---r-----   
----------------------------------------------------------------------------------------------------
6 files, 3 directories, 0 links, 0 pipes, and 0 sockets                         12288
```

이를 위해 아래 두 줄을 실행하여 User:Group에 대한 접근을 제한하였습니다.

```
sudo chmod 000 /etc/passwd
sudo chmod 000 /etc/group
```

이후 `reference/dirtree`의 실행 결과가 다음과 같습니다. Permission denied가 아닌, `1000:1000`가 출력되는 이유가 궁금합니다.
```
Name                                                        User:Group           Size     Perms Type
----------------------------------------------------------------------------------------------------
demo3
  dir1                                                      1000:1000            4096 rwx------  d
  dir2                                                      1000:1000            4096 r--------  d
  dir3                                                      1000:1000            4096 rwx------  d
    file4                                                   1000:1000               0 --x------   
    file5                                                   1000:1000               0 -w-------   
    file6                                                   1000:1000               0 r--------   
----------------------------------------------------------------------------------------------------
3 files, 3 directories, 0 links, 0 pipes, and 0 sockets                         12288
```

**Comment by Jong25** [comment]
우선 해당 예시와 같은 상황을 재현하기 위해서는 passwd와 group 파일이 아닌 해당 파일 (dir1, file4, ...)의 권한을 수정하여야 합니다. User:Group에 표시된 1000은 uid, gid의 값 (id command 입력 시 확인 가능)으로, username과 group name을 가져오기 위해 passwd, group 등의 파일을 접근해야 하는데 권한이 없어 resolution에 실패한 것 같습니다.

**Comment by YueunLee** [comment]
이러한 경우도 구현해야 하나요?

**Comment by yunjayh** [comment]
아닙니다. 이슈 가장 앞에 있는 아래와 같은 부분만 구현되면 됩니다.

> 안녕하세요, README.md 중 아래와 비슷한 출력 결과를 얻고자 테스트하는 중이었습니다.
> 
> ```
> $ dirtree -v -s demo3
> Name                                                        User:Group           Size     Perms Type 
> ----------------------------------------------------------------------------------------------------
> demo3
>   dir1                                                   sysprog:sysprog         4096 --x------  d
>     ERROR: Permission denied
>   dir2                                                   sysprog:sysprog         4096 r--------  d
>     file1                                               Permission denied
>     file2                                               Permission denied
>     file3                                               Permission denied
>   dir3                                                   sysprog:sysprog         4096 rwx------  d
>     file4                                                sysprog:sysprog            0 -----x---   
>     file5                                                sysprog:sysprog            0 ----w----   
>     file6                                                sysprog:sysprog            0 ---r-----   
> ----------------------------------------------------------------------------------------------------
> 6 files, 3 directories, 0 links, 0 pipes, and 0 sockets                         12288
> ```
