### ISSUE TITLE
채점 방식에 관하여 질문드립니다.

### ISSUE THREAD

**Issue by hyeokjujeong** [SNU-ARC/2024_spring_sysprog_Lab2#30]
reference 코드와 제 코드의 출력을 txt 파일로 받은 후 diff 함수를 사용하여 비교하면 파일의 줄끝에 있는 개행문자 차이에 의해 다르다고 나옵니다. 그래서 실제로 육안으로 비교할 경우 동일하고 차이가 있는 부분을 txt 파일로 출력할 경우에도 빈 파일이 출력됩니다. 이러한 경우에 대해서는 reference 코드와 동일하게 채점되는지 질문드리고 싶습니다.

**Comment by Jong25** [comment]
혹시 해당 내용에 관한 것일까요? https://github.com/SNU-ARC/2024_spring_sysprog_Lab2/issues/5#issuecomment-2027854765

**Comment by hyeokjujeong** [comment]
제가 오류의 이유를 착각한 것이었습니다. 각 줄 맨 뒤의 공백 개수 차이가 문제였는데 출력의 각 줄 끝의 공백 개수만 다른 것도 감점이 되는 것일까요?

**Comment by Jong25** [comment]
해당 이슈와 관련이 있는 것 같으니 확인해보시기 바랍니다. https://github.com/SNU-ARC/2024_spring_sysprog_Lab2/issues/20

**Comment by hyeokjujeong** [comment]
네 동일 내용을 확인하였습니다. 감사합니다.
