### ISSUE TITLE
제출하는 압축파일 질문

### ISSUE THREAD

**Issue by ziseoklee** [SNU-ARC/2024_spring_sysprog_Lab2#35]
Readme대로 명령어를 실행했을 때 20XX-XXXXX.tar 파일에 
src/dirtree.c 20XX-XXXXX.pdf
(src 아래 단계에 dirtree.c가 있는 구조)와 같이 압축이 되는 게 맞는지 궁금합니다.

아니라면 dirtree.c와 PDF 보고서를 같은 단계에서 압축해야 할까요?

감사합니다.

**Comment by m-joon-ixix** [comment]
저는 TA는 아니지만 이전에 같은 질문 봤어서 공유드립니다. 👉  #9
